### ISSUE TITLE
Documentation. 

### ISSUE THREAD

**Issue by sradmard** [tue-robotics/dialogflow_ros#2]
Hi,

I was wondering whether it is possible to provide some documentation on how to set up your wrapper with api.ai and ROS. 
I am trying to publish some strings into ROS using voice commands through either Amazon Alexa or Google home, and was wondering whether your wrapper would allow for that or not. 

Thank you so much in advance.

**Comment by rokusottervanger** [comment]
This is definitely possible! This project has been on hold for a few weeks, so I don't exactly remember what the status is, but the idea is that this node listens to a topic on which strings are published. It sends this string to your own API.ai agent and publishes the response. 
I will try to make some time for working out the interfaces, making sure the functionality is there and writing documentation tomorrow. I'll keep you posted.

**Comment by sradmard** [comment]
That would be great, and I would really appreciate it. I am familiar with Amazon AWS lambda function structure and how to set it up to use voice commands. That structure requires all of the required libraries to be zipped with the codes and uploaded on the Amazon AWS services. I need to familiarize myself with api.ai soon as well, but do you happen to know whether the required libraries like rospy, need to be zipped and uploaded with the codes as well on the api.ai?

**Comment by rokusottervanger** [comment]
No, that's not necessary. You build your agent in the web user interface at [API.ai](api.ai). You can then communicate with the agent through a RESTful API. This ROS wrapper just takes the string from the incoming ros message, puts it in a request to the API.ai server and publishes the server's response on another topic.

**Comment by rokusottervanger** [comment]
I added a readme to the package. If anything is still missing, let me know!
